### ISSUE TITLE
Is it necessary for each region send heartbeat to pd every 5 seconds?

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tikv#1099]
The pressure of PD increasing as region count increasing, and will limit the scale of data since PD is a single point.

**Comment by siddontang** [comment]
Yes, of course not.
When a region sends heartbeat successfully, we can delay sending for a longer time. 
Of course, if the region version changed or connects to a new PD, we must send heartbeat ASAP. 

/cc @huachaohuang

**Comment by huachaohuang** [comment]
Yep, this seems a good way to reduce the pressure, to let regions report heartbeats "as need".

For now, regions interactive with PD for three things:
1. Regions report any changes of its meta data to PD.
2. Regions report any down peers to PD for health check.
3. PD dispatches some resource balance commands to regions.

The first two things needed to be done ASAP, but they don't happen frequently, so that's fine.

As the third thing, we may let PD dispatch balance commands in store heartbeat instead of region heartbeat, and let TiKV store dispatch commands to its regions.

Well, we can have further discussion when I start optimizing on this.

**Comment by siddontang** [comment]
I think It is ok and easy to let store dispatch the commands in StoreHeartbeat response now. 
Later, after we support gRPC, we can let PD send message directly to store.
