### ISSUE TITLE
checking network between two store is slow

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1429]
In our 200T test, we find that sometimes a store doesn't receive any message, but now we don't know the reason through current log and metrics. I think first we can check whether the connection is slow or not. 

We may add a timestamp in any raft message in sampling, when the remote store receives the message, it will check the time elapsed, if it is bigger than a max value, we may think the connection is very slow and log an error. 

Of course, this may be not accurate and depends two machines having close system time, but I think it is acceptable. 

Another way is adding the Ping/Pong messages, like RTT. 

Or any other suggestions? /cc @BusyJay @hhkbp2

**Comment by ngaut** [comment]
It's not a good idea to add timestamp, a better way is to adding another health checking thread.

**Comment by BusyJay** [comment]
I think it's better to add timestamp to some sample messages (like every 100th message), so we can watch the actual latency between two store. Using health checking thread doesn't always work. For example, if there are two many messages pending in buffer, message may be queued for a long time, which can be detected by timestamp but the health checking thread.

**Comment by ngaut** [comment]
We should add a timestamp when we received the message which @BusyJay mentioned that would be queued for a long time. We should not add the timestamp when we send it.

**Comment by siddontang** [comment]
> We should add a timestamp when we received the message

This can't tell us the connection is slow, only can tell us the message is pending in raftstore channel for a long time, we can check this though metric later.

**Comment by hhkbp2** [comment]
It's essential to tell the precise goals that we want to archive. The case "messages queued in application buffer" which mentioned by @BusyJay , is not a issue directly related to network. This issue could be devided into 1. network latency 2. application queueing delay. 

For network state, there usually these indexes:

1. Connectivity
    The connection is good or not.
1. Bandwidth
    How much the bandwidth is, the used and the idle.
1. Latency
    It affects the latency of Raft replication.
1. Loss
    When there is no enough bandwidth, packages will be dropped.
1. Jitter
    It tells us whether the latency is stable or not.

IMO, we should carry out a comprehensive plan to the network state monitoring. It should has an  intuitive and independent mechanism. It should not be coupled with the other stuff, such as Raft  message or heartbeat interval, since Raft has its own high complexity.

In the other hand, because Raft messages are asynchronous and there is no timeout mechanism for them, it's not quite useful to add network state detection stuff into Raft messages. Adding timestamp into Raft message only works when the connection is good and loss rate is low. It is useless in many cases, e.g. the connection is bad, or the loss rate is high.

**Comment by BusyJay** [comment]
Actually "messages queued in application buffer" is an issue directly related to network. Because network is slow so the messages can't be sent out quickly enough. The precise goal want to archive here is a simple way to detect messages latency. We don't care about connectivity, bandwidth, latency, loss or anything else, what's concerned here is when the messages are received after it's put in the sending queue. Connectivity and anything else are just the details reason to the problem. But we need to detect the problem first.
