### ISSUE TITLE
support fuzz test?

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#252]
do we need to test some input function like codec with fuzz data? 

@ngaut 

Some tools:
- [ ] https://github.com/BurntSushi/quickcheck

**Comment by spacejam** [comment]
It's also a great idea to incorporate a simulator that can fuzz various conditions like network failures. I started down that path a bit with this: https://github.com/disasters/rasputin/blob/master/test/cluster.rs which I used for getting rasputin's consensus mechanism a bit more robust.  I would strongly recommend doing something similar by:
1. mocking any sources of time, so that they can be passed in (see how rasputin has a generic clock)
2. making the transport layer generic so that you can plug in many instances to a single test harness that simulates network failures
3. implementing quickcheck's `Arbitrary` for the simulator such that it generates sequences of failure conditions interleaved with mutation commands, and creating properties that test certain recovery semantics

**Comment by xiang90** [comment]
@spacejam Probably a separate issue for this? (we are considering adding fail points into etcd/raft, etcd)

**Comment by ngaut** [comment]
@xiang90 Good idea. We just wanna the the same thing.

**Comment by AkihiroSuda** [comment]
AFL.rs seems useful as well
https://github.com/frewsxcv/afl.rs

**Comment by ngaut** [comment]
Cool, thanks for sharing. @AkihiroSuda

**Comment by Hoverbear** [comment]
#2942 enabled this! It's minimal right now but I think this particular issue can be closed.
