### ISSUE TITLE
use latest rust version

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#2615]
Now we still use rust nightly 08-09, it is too old, we must upgrade to the latest rust version. The things we need to do are:

- [ ] select a rust version and update
- [ ] update to the newest rustfmt and format our code
- [ ] update Circle CI to use the specified rust and rustfmt
- [ ] ensure `make dev` can pass
- [ ] add the version requirement in the `build` section of READEME.md (we will provide an individual INSTALL doc later)

**Comment by Hoverbear** [comment]
I can help with these things!

Ideally we could just track stable Rust, but there are a lot of `#[feature]` uses, so that's a huge shift right now. So sticking on nightly is a good way to create forward momentum. 

Choosing a nightly release for a production project is a hard task. Recently [NLL was enabled as a feature](https://www.reddit.com/r/rust/comments/7lq5t3/featurenll_available_in_nightly/) so it would be nice to be able to utilize this moving forward. 

As for `rustfmt` I have really enjoyed [this](https://github.com/Hoverbear/digitalocean/blob/master/rustfmt.toml) configuration. It creates fairly consistent and readable code.

I can make a PR. :)

**Comment by siddontang** [comment]
Hi @Hoverbear 

We also want to use stable version but seems impossible right now. Btw, another reason is that we want to use clippy which can still be only used with nightly version.

I tried to use your rustfmt configuration, but it messed up the import order and groups sadly, maybe we can use current configuration and adjust later. 

NLL seems cool, we can use it later, I guess this can help us write borrow code easily. :-)

**Comment by Hoverbear** [comment]
Yes, it sorts the ordering of them by name. It can be turned off if there is meaning to the import orders.

**Comment by breeswish** [comment]
We are using a relatively new nightly version now thanks to @Hoverbear 's job. Closing :)
