### ISSUE TITLE
consider not to use rust

### ISSUE THREAD

**Issue by dulumao** [pingcap/tikv#3296]
太麻烦，rust现在语法都不稳定，mac linux光配置编译环境都差不多用了1天，编译还总失败, issue基本都是再问编译问题，都不如基于rocksdb从新用golang编译一个新引擎版本，cochroach用golang编译，很方便，并发也很高，不比c++开发的mysql慢多少，反而还快,tidb,pd都很好编译，kv就很麻烦，跨3个语言，要二开都麻烦，官方真心可以好好考虑下

**Comment by siddontang** [comment]
@dulumao 

What is the compiling error when you build TiKV on Linux?

**Comment by breeswish** [comment]
## Rust Compile Environment Issue

From my existing experience, the environment setup is pretty easy in Linux and MacOS. You just need to download [rustup](https://rustup.rs/) following the official instruction, and use rustup to install required rust versions as instructed in README. If you strictly follow steps in README, it should be ok. If not, please provide some details about what you did so that we can improve it and benefit others :)

## Not Using Rust

This is not something we are going to consider. Rather, replacing Golang with Rust in TiDB might be more possible :) Take CRDB as an example, it replaced core components with C++ as well, for performance considerations. For us, Rust is obviously a better solution than C++.

**Comment by breeswish** [comment]
Closing, since the topic this issue discusses about is definitely not going to be considered. Please feel free to post detailed steps and the issues you met when building TiKV.
