### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by samuelyao314** [pingcap/tikv#523]
[samuel@localhost tikv]$ make
cargo build --features dev
   Compiling rustc-serialize v0.3.19
   Compiling getopts v0.2.14
   Compiling slab v0.1.3
   Compiling log v0.3.6
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling protobuf v1.0.18 (https://github.com/stepancheg/rust-protobuf.git#a917d77d)
   Compiling libc v0.2.10
   Compiling rand v0.3.14
   Compiling uuid v0.1.18
   Compiling tempdir v0.3.4
   Compiling bitflags v0.3.3
   Compiling nix v0.5.0-pre (https://github.com/carllerche/nix-rust?rev=c4257f8a76#c4257f8a)
   Compiling quine-mc_cluskey v0.2.2
   Compiling winapi v0.2.6
   Compiling libc v0.1.12
   Compiling byteorder v0.4.2
   Compiling tipb v0.0.1 (https://github.com/pingcap/tipb.git#3df1b085)
   Compiling unicode-normalization v0.1.2
   Compiling threadpool v1.0.0
   Compiling kvproto v0.0.1 (https://github.com/pingcap/kvproto#dcb7cad2)
   Compiling regex-syntax v0.3.1
   Compiling nom v1.2.2
   Compiling bytes v0.3.0
   Compiling cfg-if v0.1.0
   Compiling semver v0.2.3
   Compiling librocksdb_sys v0.1.0 (https://github.com/ngaut/rust-rocksdb.git#015e65bb)
   Compiling rocksdb v0.3.0 (https://github.com/ngaut/rust-rocksdb.git#015e65bb)
   Compiling bytes v0.3.0 (https://github.com/carllerche/bytes#12dfc417)
   Compiling time v0.1.35
   Compiling quick-error v0.2.2
   Compiling toml v0.1.28
   Compiling clippy v0.0.63
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/utils/hir.rs:335:13: 335:39 error: this pattern has 3 fields, but the corresponding variant has 4 fields [E0023]
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/utils/hir.rs:335             ExprClosure(cap, _, ref b) => {
                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/utils/hir.rs:335:13: 335:39 help: run `rustc --explain E0023` to see a detailed explanation
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/utils/hir.rs:336:43: 336:54 error: mismatched types:
 expected `fn(_, _, _) -> _`,
    found `fn(rustc::hir::CaptureClause, syntax::ptr::P<rustc::hir::FnDecl>, syntax::ptr::P<rustc::hir::Block>, syntax::codemap::Span) -> rustc::hir::Expr_ {rustc::hir::ExprClosure}` (incorrect number of function parameters) [E0308]
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/utils/hir.rs:336                 let c: fn(_, _, _) -> _ = ExprClosure;
                                                                                                                                          ^~~~~~~~~~~
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/utils/hir.rs:336:43: 336:54 help: run `rustc --explain E0308` to see a detailed explanation
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/block_in_if_condition.rs:46:16: 46:44 error: this pattern has 3 fields, but the corresponding variant has 4 fields [E0023]
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/block_in_if_condition.rs:46         if let ExprClosure(_, _, ref block) = expr.node {
                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/block_in_if_condition.rs:46:16: 46:44 help: run `rustc --explain E0023` to see a detailed explanation
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/eta_reduction.rs:43:12: 43:45 error: this pattern has 3 fields, but the corresponding variant has 4 fields [E0023]
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/eta_reduction.rs:43     if let ExprClosure(_, ref decl, ref blk) = expr.node {
                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/eta_reduction.rs:43:12: 43:45 help: run `rustc --explain E0023` to see a detailed explanation
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/map_clone.rs:29:21: 29:54 error: this pattern has 3 fields, but the corresponding variant has 4 fields [E0023]
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/map_clone.rs:29                     ExprClosure(_, ref decl, ref blk) => {
                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/map_clone.rs:29:21: 29:54 help: run `rustc --explain E0023` to see a detailed explanation
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/misc_early.rs:131:24: 131:65 error: this pattern has 3 fields, but the corresponding variant has 4 fields [E0023]
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/misc_early.rs:131                 if let ExprKind::Closure(_, ref decl, ref block) = closure.node {
                                                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/misc_early.rs:131:24: 131:65 help: run `rustc --explain E0023` to see a detailed explanation
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/misc_early.rs:153:21: 153:45 error: this pattern has 3 fields, but the corresponding variant has 4 fields [E0023]
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/misc_early.rs:153                 let ExprKind::Closure(_,_,_) = t.node,
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/misc_early.rs:153:21: 153:45 note: in this expansion of if_let_chain! (defined in /home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/utils/mod.rs)
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/misc_early.rs:153:21: 153:45 note: in this expansion of if_let_chain! (defined in /home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/utils/mod.rs)
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/misc_early.rs:153:21: 153:45 note: in this expansion of if_let_chain! (defined in /home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/utils/mod.rs)
/home/samuel/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.63/src/misc_early.rs:153:21: 153:45 help: run `rustc --explain E0023` to see a detailed explanation
error: aborting due to 7 previous errors
error: Could not compile `clippy`.

To learn more, run the command again with --verbose.

**Comment by siddontang** [comment]
what's your rust version?

you can use `make release` to disable clippy compile.

**Comment by BusyJay** [comment]
Or `ENABLE_FEATURES=default make`.

Maybe we should use beta version of rust. @ngaut

**Comment by ngaut** [comment]
We may use beta version after our dependency(rustfmt, clippy) shift to beta.

**Comment by lisawzw** [comment]
I met the same question

[root@tidb tikv]# rustc -V
rustc 1.12.0-nightly (7ad125c4e 2016-07-11)
[root@tidb tikv]# make
cargo build --features dev
   Compiling bytes v0.3.0
   Compiling typeable v0.1.2
   Compiling libc v0.2.11
   Compiling rand v0.3.14
   Compiling winapi-build v0.1.1
   Compiling ws2_32-sys v0.2.1
   Compiling kernel32-sys v0.2.2
   Compiling bitflags v0.4.0
   Compiling nix v0.5.1
   Compiling fs2 v0.2.4
   Compiling url v1.1.1
   Compiling uuid v0.1.18
   Compiling tempdir v0.3.4
   Compiling libc v0.1.12
   Compiling lazy_static v0.1.16
   Compiling crc v1.2.0
   Compiling librocksdb_sys v0.1.0 (https://github.com/ngaut/rust-rocksdb.git#ebf9de0f)
   Compiling rocksdb v0.3.0 (https://github.com/ngaut/rust-rocksdb.git#ebf9de0f)
   Compiling nix v0.5.0-pre (https://github.com/carllerche/nix-rust?rev=c4257f8a76#c4257f8a)
   Compiling time v0.1.35
   Compiling clippy_lints v0.0.76
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/items_after_statements.rs:50:20: 50:35 error: failed to resolve. Use of undeclared type or module `DeclKind` [E0433]
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/items_after_statements.rs:50             if let DeclKind::Local(_) = decl.node {
                                                                                                                              ^~~~~~~~~~~~~~~
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/items_after_statements.rs:50:20: 50:35 help: run `rustc --explain E0433` to see a detailed explanation
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/items_after_statements.rs:57:24: 57:38 error: failed to resolve. Use of undeclared type or module `DeclKind` [E0433]
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/items_after_statements.rs:57                 if let DeclKind::Item(ref it) = decl.node {
                                                                                                                                  ^~~~~~~~~~~~~~
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/items_after_statements.rs:57:24: 57:38 help: run `rustc --explain E0433` to see a detailed explanation
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/misc_early.rs:151:21: 151:36 error: failed to resolve. Use of undeclared type or module `DeclKind` [E0433]
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/misc_early.rs:151                 let DeclKind::Local(ref local) = first.node,
                                                                                                                    ^~~~~~~~~~~~~~~
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/utils/mod.rs:54:12: 54:46 note: in this expansion of if_let_chain! (defined in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/utils/mod.rs)
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/misc_early.rs:149:13: 163:15 note: in this expansion of if_let_chain! (defined in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/utils/mod.rs)
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/misc_early.rs:151:21: 151:36 help: run `rustc --explain E0433` to see a detailed explanation
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/returns.rs:96:17: 96:32 error: failed to resolve. Use of undeclared type or module `DeclKind` [E0433]
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/returns.rs:96             let DeclKind::Local(ref local) = decl.node,
                                                                                                            ^~~~~~~~~~~~~~~
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/utils/mod.rs:54:12: 54:46 note: in this expansion of if_let_chain! (defined in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/utils/mod.rs)
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/utils/mod.rs:54:12: 54:46 note: in this expansion of if_let_chain! (defined in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/utils/mod.rs)
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/returns.rs:92:9: 110:11 note: in this expansion of if_let_chain! (defined in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/utils/mod.rs)
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/returns.rs:96:17: 96:32 help: run `rustc --explain E0433` to see a detailed explanation
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/non_expressive_names.rs:71:22: 71:33 error: wrong number of lifetime parameters: expected 0, found 1 [E0107]
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/non_expressive_names.rs:71 impl<'v, 'a, 'b, 'c> Visitor<'v> for SimilarNamesNameVisitor<'a, 'b, 'c> {
                                                                                                                              ^~~~~~~~~~~
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/non_expressive_names.rs:71:22: 71:33 help: run `rustc --explain E0107` to see a detailed explanation
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/non_expressive_names.rs:229:18: 229:29 error: wrong number of lifetime parameters: expected 0, found 1 [E0107]
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/non_expressive_names.rs:229 impl<'v, 'a, 'b> Visitor<'v> for SimilarNamesLocalVisitor<'a, 'b> {
                                                                                                                           ^~~~~~~~~~~
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.76/src/non_expressive_names.rs:229:18: 229:29 help: run `rustc --explain E0107` to see a detailed explanation
error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
error: Could not compile `clippy_lints`.

To learn more, run the command again with --verbose.
make: *** [build] Error 101
[root@tidb tikv]# make release
cargo build --release --bin tikv-server
   Compiling bytes v0.3.0
   Compiling unicode-normalization v0.1.2
   Compiling bitflags v0.3.3
   Compiling traitobject v0.0.1
   Compiling void v1.0.2
   Compiling slab v0.1.3
   Compiling matches v0.1.2
   Compiling unicode-bidi v0.2.3
   Compiling semver v0.1.20
   Compiling libc v0.1.12
   Compiling rustc-serialize v0.3.19
   Compiling num-traits v0.1.32
   Compiling num-integer v0.1.32
   Compiling idna v0.1.0
   Compiling url v1.1.1
   Compiling lazy_static v0.1.16
   Compiling crc v1.2.0
   Compiling quick-error v0.2.2
   Compiling cfg-if v0.1.0
   Compiling protobuf v1.0.20 (https://github.com/stepancheg/rust-protobuf.git#668cbcd4)
   Compiling num-complex v0.1.32
   Compiling winapi v0.2.6
   Compiling byteorder v0.5.1
   Compiling httparse v1.1.2
   Compiling winapi-build v0.1.1
   Compiling language-tags v0.2.2
   Compiling spmc v0.2.1
   Compiling num-iter v0.1.32
   Compiling threadpool v1.3.0
   Compiling ws2_32-sys v0.2.1
   Compiling typeable v0.1.2
   Compiling toml v0.1.28
   Compiling libc v0.2.11
   Compiling nix v0.5.0-pre (https://github.com/carllerche/nix-rust?rev=c4257f8a76#c4257f8a)
   Compiling rand v0.3.14
   Compiling uuid v0.1.18
   Compiling tempdir v0.3.4
   Compiling librocksdb_sys v0.1.0 (https://github.com/ngaut/rust-rocksdb.git#ebf9de0f)
   Compiling rocksdb v0.3.0 (https://github.com/ngaut/rust-rocksdb.git#ebf9de0f)
   Compiling log v0.3.6
   Compiling mime v0.2.1
   Compiling cadence v0.5.1
   Compiling kernel32-sys v0.2.2
   Compiling vecio v0.1.0
   Compiling rustc_version v0.1.7
   Compiling nix v0.6.0
   Compiling unicase v1.4.0
   Compiling num-bigint v0.1.32
   Compiling net2 v0.2.23
   Compiling fs2 v0.2.4
   Compiling time v0.1.35
   Compiling cookie v0.2.5
   Compiling miow v0.1.2
   Compiling mio v0.5.0 (https://github.com/carllerche/mio.git#7d4778f2)
   Compiling num-rational v0.1.32
   Compiling num v0.1.32
   Compiling bitflags v0.4.0
   Compiling nix v0.5.1
   Compiling tipb v0.0.1 (https://github.com/pingcap/tipb.git#4140a6e6)
   Compiling kvproto v0.0.1 (https://github.com/pingcap/kvproto#f89c1ea9)
   Compiling mio v0.5.1
   Compiling rotor v0.6.3
   Compiling hyper v0.9.4 (https://github.com/hyperium/hyper.git#67436c5b)
   Compiling getopts v0.2.14 (https://github.com/rust-lang-nursery/getopts#4dfc197a)
   Compiling tikv v0.0.1 (file:///src/github.com/pingcap/tikv)
src/lib.rs:22:12: 22:22 warning: this feature has been stable since 1.11.0. Attribute no longer needed, #[warn(stable_features)] on by default
src/lib.rs:22 #![feature(iter_arith)]
                         ^~~~~~~~~~
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/src/github.com/pingcap/tikv/target/release/tikv_server.0.o" "-o" "/src/github.com/pingcap/tikv/target/release/tikv_server" "-Wl,--gc-sections" "-pie" "-Wl,-O1" "-nodefaultlibs" "-L" "/src/github.com/pingcap/tikv/target/release" "-L" "/src/github.com/pingcap/tikv/target/release/deps" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/src/github.com/pingcap/tikv/target/release/deps/libtoml-88c2092368f85c4f.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libfs2-78ccc7fbf1e1ae18.rlib" "/src/github.com/pingcap/tikv/target/release/libtikv.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libnix-c1e6d03f33fcdbb4.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libcadence-9576ac57842bcf06.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libnum-f6961afa9fa1a02b.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libnum_rational-576f79d570f1b9fd.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libnum_complex-6a8fb72fb99d524f.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libthreadpool-fad72996148b2f07.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libtipb-6ea80d2d576da521.rlib" "/src/github.com/pingcap/tikv/target/release/deps/librocksdb-7a44dca17654e942.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libtempdir-a136a238b008f647.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libmio-2d9ad9925bada084.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libnix-f8d033ce6354dacb.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-c8005792.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-c8005792.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libbitflags-e61ad67c3301e77d.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libgetopts-82790631581b1d43.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libnum_bigint-0f2c1e47b214fd65.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libkvproto-b8a85b01f8205945.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libprotobuf-6a49bfd14e8dbeda.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libhyper-ab826e5e5468c58f.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libtraitobject-516160771d9db60e.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libspmc-65d74c9afc8f1191.rlib" "/src/github.com/pingcap/tikv/target/release/deps/librotor-afe7c064411f450c.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libmio-4cd51b3d244c94b3.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libnet2-3c7950c09adfba48.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libws2_32-c73408aa15cb2b6f.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libkernel32-df86a08647459244.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libcfg_if-72c1f992b13d5087.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libmiow-b827bf6129dcd844.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libnix-e3c0cb7ca8e41f17.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libbitflags-75746cc7f0e9d928.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libbytes-f9fbfc75eb2416e0.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libvoid-2cc31605fcb01ba1.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libquick_error-92f249c4e55991b4.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libhttparse-36b96d90ffbce562.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libcookie-1f264fccb02ef6c6.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libtime-750bfdd52feafcb7.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libmime-40ee41a2f2e225b0.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libwinapi-0f5f77a5f89d9e92.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libunicase-87c5f8ba3db67fd3.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libbyteorder-c882ee50a4e0aa4f.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libtypeable-ad302c7c6ce39362.rlib" "/src/github.com/pingcap/tikv/target/release/deps/liblibrocksdb_sys-f3a3d7f876a016af.rlib" "/src/github.com/pingcap/tikv/target/release/deps/liblibc-0c57a2126eb1e7e8.rlib" "/src/github.com/pingcap/tikv/target/release/deps/liburl-4690728b1e11fab3.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libidna-82ebdb343d6c1855.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libunicode_normalization-5de3a9c8fd8ddf4e.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libunicode_bidi-04ad1da5552425fd.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libmatches-5d5580ffd528031c.rlib" "/src/github.com/pingcap/tikv/target/release/deps/liblanguage_tags-abe5f88450030754.rlib" "/src/github.com/pingcap/tikv/target/release/deps/liblog-bf16bb9a4912b11d.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libslab-4f8b9e9b6e35857c.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libnum_iter-50df698bc905252c.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libnum_integer-52fdddf28cd8e924.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libnum_traits-555e3a6260c26680.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libcrc-1fceeef3c778b3f2.rlib" "/src/github.com/pingcap/tikv/target/release/deps/liblazy_static-3a04918be71c80ee.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-c8005792.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libvecio-a8bbfadebfac7101.rlib" "/src/github.com/pingcap/tikv/target/release/deps/libuuid-13c4decae1c5ee4b.rlib" "/src/github.com/pingcap/tikv/target/release/deps/librand-49a08859d086fffe.rlib" "/src/github.com/pingcap/tikv/target/release/deps/liblibc-6b483f9a7097e9a4.rlib" "/src/github.com/pingcap/tikv/target/release/deps/librustc_serialize-3561541d79c18212.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-c8005792.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-c8005792.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-c8005792.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-c8005792.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-c8005792.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-c8005792.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-c8005792.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-c8005792.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-c8005792.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-c8005792.rlib" "-l" "rocksdb" "-l" "c" "-l" "m" "-l" "util" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-l" "compiler-rt"
note: /usr/bin/ld: cannot find -lrocksdb
collect2: ld returned 1 exit status

error: aborting due to previous error
error: Could not compile `tikv`.

To learn more, run the command again with --verbose.
make: *** [release] Error 101
Await beta version!

**Comment by ngaut** [comment]
link to rocksdb failed. Try "make deps && make release"

**Comment by lisawzw** [comment]
It's successful,My environment has some questions,Thanks@ngaut
