### ISSUE TITLE
Sync TiDB cluster between domestic and oversea ?

### ISSUE THREAD

**Issue by terryzhao** [pingcap/tikv#935]
Hi Guys, 

Now ,i'm facing an issue that  i want to deploy two TiDB clusters, one is deployed in domestic on aliyun and the other is on aws HK/US.

In China , i deployed cluster including 3 nodes (A, B, C), and for Oversea cluster which includes four nodes (D, E, F, G). 
I have the one-to-one transnational network connection solution.   That means the network connection between A and D is OK, but other connection paths (ex: A-2-E, B-2-F ...) are not reached. 

Actually,  i want the data on cluster Home and cluster Oversea is synced.  Could you tell me if TiDB support this scenario? if Yes, could you give me a guilder ? 

Thanks!

**Comment by siddontang** [comment]
Hi @terryzhao 

You have 7 nodes, so at lease 4 nodes are needed. So the leader must be in D, E, F, G, and you said that only A - D is connective, so you should ensure all regions leaders are in D, so A can sync data, but unlucky, B and C can't have any data, because A is follower and can't send data to them.

**Comment by terryzhao** [comment]
Hi @siddontang ,

Thanks very much!
