### ISSUE TITLE
check incoming message's store id validation

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#973]
Let's assume following scenario:

+ We start 3 TiKV a, b, c, all servers listening 20160, then we remove the cluster and want to start a new one. 
+ We remove TiKV a and b and all PD data, but unfortunately, we forget to remove c. 
+ We begin to bootstrap a new cluster, we first start PD, and then start another TiKV a' with previous listening 20160. 

Because an old TiKV C sends message to previous a and b, so the newer a' can receives this message too, then a' want to response to c, so it let PD tell c's address, but PD can't know and output the error log like : 

```
2016/08/25 15:15:35 conn.go:100: [error] handle request header:<uuid:"2I\013b\005\037F\310\234!1U\023\342h\353" cluster_id:1 > cmd_type:GetStore get_store:<store_id:5 >  err /home/xxx/go/src/github.com/pingcap/pd/server/cluster.go:360: invalid store ID 5, not found
/home/shenli/go/src/github.com/pingcap/pd/server/command.go:125:
```

If TiKV receives a message from an unknown store, maybe we should check whether this store is valid or not in PD. 
If a TiKV starts, it must register to PD first, then work, so if we see an unknown store id and not in PD, we can ensure this is an invalid message. 

This may happen frequently in our own development environment, we share the same development machines and usually run the cluster without isolation, so old remaining cluster may affect the new started one. of course this can't corrupt the data.

Do we need to check this? 

/cc @ngaut  @qiuyesuifeng @shenli @hhkbp2

**Comment by BusyJay** [comment]
I don't think we need to check this. If the nodes share the same cluster id, they should be considered in the same cluster.

**Comment by hhkbp2** [comment]
@BusyJay @siddontang 
IMO, this issue is one part of the healthy checking for the same 'deployment mistake' problem. There are https://github.com/pingcap/pd/issues/287
And the previous PRs have been merged into TiKV and PD.
We should have a overall plan for dealing this problem and make it clear how far to go for this checking. If some issue is not needed, maybe we could wipe it out before implement it at Beta3.

@ngaut suggests that the certificate mechanism could be used to isolate cluster.

**Comment by hhkbp2** [comment]
Close issue with PR #1011
