### ISSUE TITLE
batch region raft ready 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#996]
Now the flow for a region raft ready is:
1.  send msg if leader
2. append msgs to raft log
3. response to leader if follower
4. apply committed log

For 2 and 4, we will do a WriteBatch each, if we handle multi regions ready at same time, we will do many WriteBatch writes. 
But we can combine these, only using two WriteBatch for all regions, one is for 2 and the other is for 4.

So the flow may:
- Travel all ready regions and do 1 and 2 and then commit the WriteBatch
- Travel all ready regions and do 3 and 4 and then commit the WriteBatch

why not combine all into one WriteBatch? In raft, we must guarantee msgs are appended to raft log before responding to leader.

/cc @ngaut @BusyJay

**Comment by hhkbp2** [comment]
#994 related

**Comment by siddontang** [comment]
@hhkbp2 

Although we use batch here, we will still estimate whether using sync write or not here.

**Comment by hhkbp2** [comment]
@siddontang 
Sooner or later, both of these require their implementation:

1. sync raft log to hard drive before applying(for leader)/ confirming log to leader(for follower).
2. tuning performance, using method like batch write(multi log entries share a single fsync/fdatasync, avg latency increases but throughput increases), async write, increase concurrency

It's better to carry out them in a sequence like 1 -> 2, since correctness comes first than performance.
If we get 2 done first, probably we have to twist the code some way again to improve performance again after 1 is brought up.

**Comment by xiang90** [comment]
> avg latency increases but throughput increases

It depends. If we do batching smartly (correctly?), the latency can be similar under light load, but smaller under heavy load. As I mentioned before, I would suggest to make sure everything correct first. :)
